### ISSUE TITLE
Not Global Mode

### ISSUE THREAD

**Issue by hamedyosefian** [tzmax/V2RayXS#31]
I use global mode and work in all browser very good 
but not work in telegram and other app install on my mac and just on browser

**Comment by tzmax** [comment]
@hamedyosefian I'm sorry for the confusion caused by the naming of the global mode. In fact, it should probably be called the system proxy mode (but due to historical reasons, I think this naming can be retained). As for some software, they do not pass the system proxy by default or do not support manual settings proxy (such as the famous Xcode) can refer to https://github.com/tzmax/V2RayXS/issues/30

**Comment by livingfree2023** [comment]
> I use global mode and work in all browser very good but not work in telegram and other app install on my mac and just on browser

For Telegram you can either
1. Use "TUN model" from drop down menu
or 
2. Find out your local Socks 5 port in V2RayXS/Configure (e.g. 1080) and in your Telegram's Proxy setting, put 127.0.0.1:1080

**Comment by hamedyosefian** [comment]
> > I use global mode and work in all browser very good but not work in telegram and other app install on my mac and just on browser
> 
> For Telegram you can either
> 
> 1. Use "TUN model" from drop down menu
>    or
> 2. Find out your local Socks 5 port in V2RayXS/Configure (e.g. 1080) and in your Telegram's Proxy setting, put 127.0.0.1:1080

second plan is very good tnx
TUN not work for me

**Comment by hamedyosefian** [comment]
@tzmax 

TUN mode not work for me and disconnected
I use this doc :https://github.com/tzmax/V2RayXS#have-you-encountered-a-problem
but still not work

**Comment by tzmax** [comment]
@hamedyosefian you are invited to join the v1.5.7 beta, If there is a problem, let us keep in touch
